apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  selector:
    matchLabels:
      app: angular-app
  replicas: 1
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - image: docker.io/library/angular-env-variables:v1
        name: angular-env-variables
        imagePullPolicy: Never
        ports:
          - containerPort: 80
        env:
        - name: NG_APP_ENV
          value: PROD_KUBE
        - name: NG_GOOGLE_MAPS_KEY
          value: KUBE_GOOGLE_KEY_8798452

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: angular-service
# spec:
#   selector:
#     app: angular-service
#   ports:
#   - protocol: TCP
#     port: 8080
#     targetPort: 8080
#   type: NodePort