apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - image: docker.io/library/angular-env-variables:v1
        name: angular-env-variables
        imagePullPolicy: Never
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: angular-configmap
        # env:
        # - name: NG_APP_ENV
        #   value: PROD_KUBE
        # - name: NG_GOOGLE_MAPS_KEY
        #   value: KUBE_GOOGLE_KEY_8798452
