apiVersion: v1
kind: Service
metadata:
  name: angular-service
  labels:
    app: angular-service
spec:
  type: LoadBalancer
  ports:
    - port: 8001
      protocol: TCP
      targetPort: 80
  selector:
    app: angular-app


